CoffeeShop/Models/Item.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using Microsoft.AspNetCore.Http;

namespace CoffeeShop.Models
{
    public class Item
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public decimal Price { get; set; }
        public string ProductDescription { get; set; }

        public string ItemImage { get; set; }

        public int? Quantity { get; set; }


        [Display(Name = "Product Type")]
        public int ProductTypeId { get; set; }
        [ForeignKey("ProductTypeId")]
        public ProductTypes ProductTypes { get; set; }
    }
}

CoffeeShop/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoffeeShop.Data;
using CoffeeShop.Models;
using Microsoft.AspNetCore.Http;
using CoffeeShop.Utitlity;
using System.IO;
using System.Net.Http.Headers;
using static System.Net.Mime.MediaTypeNames;

namespace CoffeeShop.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Items.Include(i => i.ProductTypes);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.ProductTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        ////public async Task<IActionResult> Create([Bind("Id,Name,Price,ProductDescription,ItemImage,ProductTypeId")] Item item
        ////    , IFormFile images)
        ////{
        ////    if (ModelState.IsValid)
        ////    {
        ////        _context.Add(item);
        ////        await _context.SaveChangesAsync();
        ////        return RedirectToAction(nameof(Index));
        ////    }
        ////    ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType", item.ProductTypeId);
        ////    return View(item);
        ////}
        ///
        public async Task<IActionResult> Create(Item item, IFormFile FormFile)
        {
            if (ModelState.IsValid)
            {
                var filePath = "";
                var dbPath = "";
                var filenames = "";

                if (FormFile != null)
                {
                    // check extension
                    string ext = Path.GetExtension(FormFile.FileName);
                    //if (ext == ".pdf")
                    //{
                    filenames = FormFile.FileName.Replace(" ", "-");
                    //get file name
                    // var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Trim('"');
                    var filename = ContentDispositionHeaderValue.Parse(FormFile.ContentDisposition).FileName.Replace(" ", "-");


                    //get path
                    var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images");

                    //var MainPath = Path.Combine("DocUploads");

                    //create directory "Uploads" if it doesn't exists
                    if (!Directory.Exists(MainPath))
                    {
                        Directory.CreateDirectory(MainPath);
                    }

                    //get file path 
                    //filePath = Path.Combine(MainPath, FormFile.FileName);
                    filePath = Path.Combine(MainPath, filenames);
                    dbPath = Path.Combine("Images", filenames);
                    using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
                    {
                        await FormFile.CopyToAsync(stream);
                    }

                    //get extension
                    string extension = Path.GetExtension(filename);
                    
                }
                
                item.ItemImage = "Images/" + FormFile.FileName;
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType", item.ProductTypeId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,ProductDescription,ItemImage,ProductTypeId")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductTypeId"] = new SelectList(_context.ProductTypes, "Id", "ProductType", item.ProductTypeId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.ProductTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.Id == id);
        }


        //Product details
        [HttpPost]
        [ActionName("Details")]
        public async Task<IActionResult> ProductDetails(int? id, Item itemR)
        {
            List<Item> items = new List<Item>();
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .Include(i => i.ProductTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }
            items = HttpContext.Session.Get<List<Item>>("items");
            if (items == null)
            {
                items = new List<Item>();
            }
            item.Quantity= itemR.Quantity;
            items.Add(item);
            HttpContext.Session.Set("items", items);
            return View(item);
        }

        public async Task<IActionResult> Cart()
        {
            List<Item> items = HttpContext.Session.Get<List<Item>>("items");
            if (items == null)
            {
                items = new List<Item>();
            }
            return View(items);
        }


        // Remove
        public async Task<IActionResult> Remove(int? id)
        {
            List<Item> items = HttpContext.Session.Get<List<Item>>("items");
            if (items != null)
            {
                var item = _context.Items.FirstOrDefault(i => i.Id == id);
                if (item != null)
                {
                    items.Remove(item);
                    HttpContext.Session.Set("items", items);
                }
                items = new List<Item>();
            }
            return View("Index");
        }
    }
}

CoffeeShop/Controllers/OrdersController.cs
using CoffeeShop.Data;
using CoffeeShop.Models;
using CoffeeShop.Utitlity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CheckOut()
        {
            var userInfo = HttpContext.Session.GetString("Userdetails");

            var entitty = _context.Users.Where(e => e.Password == userInfo).FirstOrDefault();

            HttpContext.Session.SetString("name", entitty.Name);
            HttpContext.Session.SetString("phone", entitty.PhoneNumber);
            HttpContext.Session.SetString("email", entitty.Email);
            HttpContext.Session.SetString("address", entitty.Address);
            //HttpContext.Session.Set("name", entitty.Name);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckOut(Order order)
        {
            List<Item> items = HttpContext.Session.Get<List<Item>>("items");
            if (items != null)
            {
                foreach (var item in items)
                {
                    order.OrderDate = DateTime.Now.Date;
                    OrderDetails orderDetails = new OrderDetails();
                    orderDetails.ItemId = item.Id;
                    orderDetails.Quantity = item.Quantity;
                    order.OrderDetails.Add(orderDetails);

                }
            }
            order.OrderNo = GetOrderNo();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Set("items", new List<Item>());
            ViewBag.Order = "Your Order is placed successfully";
            return View();
        }


        public string GetOrderNo()
        {
            int rowCount = _context.Orders.ToList().Count() + 1;
            return rowCount.ToString("000");
        }


        public async Task<IActionResult> OrderList()
        {

            List<Order> orders = _context.Orders.ToList();
            List<OrderDetails> odetails = _context.OrderDetails.ToList();
            List<Item> items = _context.Items.ToList();

            var orderList = from e in orders
                                 join d in odetails on e.Id equals d.OrderId into table1
                                 from d in table1.ToList()
                                 join i in items on d.ItemId equals i.Id into table2
                                 from i in table2.ToList()
                                 select new OrderListVm
                                 {
                                     Name = e.Name,
                                     PhoneNo = e.PhoneNo,
                                     Address = e.Address,
                                     OrderDate = e.OrderDate,
                                     OrderNo = e.OrderNo,
                                     itemName = i.Name,
                                     Price = i.Price,
                                     Quantity = Convert.ToInt32(d.Quantity),
                                     TotalPrice = i.Price * Convert.ToInt32(d.Quantity)
                                 };
            return View(orderList.Where(o => o.OrderDate == DateTime.Today));

        }
    }
}

CoffeeShop/Views/Items/Cart.cshtml
@model IEnumerable<CoffeeShop.Models.Item>
@{
    ViewData["Title"] = "Cart";
}

<h1>Your Cart</h1>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Category</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>  <img src="/@item.ItemImage" alt="Card Image" class="card-img-top" style="height:150px" /></td>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.ProductDescription</td>
                    <td>@item.Quantity</td>
                    <td>@item.ProductTypes.ProductType</td>
                   
                    @*<td>
                        <a asp-action="Remove" asp-controller="Items">
                            <i class="bi bi-trash" style="width:150px" ></i>
                        </a>
                    </td>*@
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-6">
        <a asp-action="Index" asp-controller="Items" class="btn btn-success"> Back To Home</a>
    </div>
    <div class="col-6 text-right">
        <h5>Total Amount:</h5>
        <h5>Grand Total : @Model.Sum(p => p.Price * p.Quantity)</h5>
        <a asp-action="CheckOut" asp-controller="Orders" class="btn btn-info"> Proceed To Check Out</a>
    </div>
</div>

CoffeeShop/Views/Items/Create.cshtml
@model CoffeeShop.Models.Item

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemImage" class="control-label"></label>
               @* <input asp-for="ItemImage" name="FormFile" class="form-control" type="file" />*@
                <input name="FormFile" class="form-control" type="file" />
                <span asp-validation-for="ItemImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <select asp-for="ProductTypeId" class ="form-control" asp-items="ViewBag.ProductTypeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoffeeShop/Views/Items/Delete.cshtml
@model CoffeeShop.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductTypes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductTypes.ProductType)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoffeeShop/Views/Items/Details.cshtml
@model CoffeeShop.Models.Item

@{
    ViewData["Title"] = "Details";
}



<h4>Item Details</h4>
<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                Name : <input asp-for="Name" class="form-control" readonly />

            </div>
            <div class="form-group">

                Price : <input asp-for="Price" class="form-control" readonly />

            </div>
            <div class="form-group">
                Description : <input asp-for="ProductDescription" class="form-control" readonly />

            </div>

            <div class="form-group">

                Category : <input asp-for="ProductTypes.ProductType" class="form-control" readonly />
            </div>
            <div class="form-group">

                Quantity :<select class="form-control" name="Quantity" id="Quantity">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add to Cart" class="btn btn-info" />
            </div>
        </form>
    </div>
    <div class="col-3">
        <div class="form-group">
            <label asp-for="ItemImage" class="control-label"></label>
            <img src="~/@Model.ItemImage" width="100%" height="250px" style="border-radius;5px; border:1px solid #efefef " />
            @*<img src="~/Images/noimage.png" width="100%" height="250px" style="border-radius;5px; border:1px solid #efefef " />*@

        </div>
    </div>
</div>

<div>
    <a asp-action="Index" , asp-controller="Home">Back to List</a>
</div>

CoffeeShop/Views/Items/Edit.cshtml
@model CoffeeShop.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemImage" class="control-label"></label>
                @* <input asp-for="ItemImage" name="FormFile" class="form-control" type="file" />*@
                <input name="FormFile" class="form-control" type="file" />
                <span asp-validation-for="ItemImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <select asp-for="ProductTypeId" class="form-control" asp-items="ViewBag.ProductTypeId"></select>
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoffeeShop/Views/Items/Index.cshtml
@model IEnumerable<CoffeeShop.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="container-fluid py-4">
    <h4 class="text-center text-uppercase">ITEM List</h4>
    <table class="table table-striped table-bordered">
        <thead class="bg-dark text-white">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ItemImage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductTypes)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemImage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductTypes.ProductType)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>